### PR TITLE
bump version to 9.7.0

### LINKED ISSUE #153: update populate-releases and version number on master
There was a typo in the populate script,  and the version number should now be 9.7.0 not 9.7build

### PR DESCRIPTION
**Pull request by troy2914**
also remove an extra s from a var name.

fixes #153

### CODE REVIEW

**Review by clevengr — CHANGES_REQUESTED** [review]
Why are these changes being merged directly into master?  That will put develop out of sync with master.  It seems like these should be merged to develop, followed by merging develop to master, like all other changes.

**Comment by troy2914** [comment]
Because the version part is specific to master.

**Comment by clevengr** [comment]
> Because the version part is specific to master.

Nevertheless, doesn't doing it this way mean that develop will be out of sync with master, requiring a merge from master to develop?  That seems backwards and awkward...

**Comment by troy2914** [comment]
so you want a 9.7.0-6166.develop ? followed with a 9.7.0-6167 release candidate?

**Comment by troy2914** [comment]
> so you want a 9.7.0-6166.develop ? followed with a 9.7.0-6167 release candidate?

followed by a 9.8build-6168.develop ?

**Comment by clevengr** [comment]
> > so you want a 9.7.0-6166.develop ? followed with a 9.7.0-6167 release candidate?
> 
> followed by a 9.8build-6168.develop ?

Ok, I see that problem.  But aren't we going to have a similar problem if we push to master?  Don't we then have to merge master to develop (to keep develop in sync with master), which will generate a new Nightly Build?

**Comment by troy2914** [comment]
the other merge request is for develop to fix the populate script and change to 9.8build.
so with this MR we get 9.7.0-6166 release candidate
and with the other MR we get a 9.8build-6167

**Review by clevengr — APPROVED** [review]

**Pull request merged**
