### PR TITLE
I607 Interim fix for issue #607 "Add a compile time limit".  

### PR DESCRIPTION
**Pull request by johnbrvc**
This is a temporary fix to deal with runaway compiles.  It makes use of a shell script shim to be inserted before any compile command that you wish to limit.

### Description of what the PR does
Adds a shell script to the scripts folder called `dotimedcompile.sh`.  This script provides a mechanism to limit the CPU time and file sizes for compiles.  It is meant to be prepended to existing compile commands, eg:

`dotimedcompile.sh 30 128 /usr/bin/g++ -g -O2 -std=gnu++20 -static ...
`
### Issue which the PR addresses
This temporarily addresses #607.  607 will be closed by this PR, leaving PR 425 still open which will be addressed later when a non-interim fix is coded.

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Ubuntu 22.04
Java 1.8

### Precise steps for _testing_ the PR 
1) From the administrator client, modify a language as shown above.  
2) Make a C++ submission using the attached program.
[stress_test.txt](https://github.com/pc2ccs/pc2v9/files/12690511/stress_test.txt)
3) Note that it will compile for a while but will eventually be killed due to exceeding the time limit

### CODE REVIEW

**Review by troy2914 — APPROVED** [review]
Seems reasonable for now.

**Comment by clevengr** [comment]
As I understand it, the usage of this script would be to prepend it to a given _language_ definition.  However, it is accepting a hard-coded numeric argument for compilation time, which is a per-_problem_ attribute (see the CLICS specification for the Problem Package Format; specifically, the [limits section](https://icpc.io/problem-package-format/spec/problem_package_format#limits) of the `problem.yaml` file).  If a contest is configured with problems having different compilation time limits, the approach taken in the PR will not work.

Is there an existing substitution variable that could be used (instead of a hard-coded time limit) to solve this issue?

**Comment by troy2914** [comment]
> As I understand it, the usage of this script would be to prepend it to a given _language_ definition. However, it is accepting a hard-coded numeric argument for compilation time, which is a per-_problem_ attribute (see the CLICS specification for the Problem Package Format; specifically, the [limits section](https://icpc.io/problem-package-format/spec/problem_package_format#limits) of the `problem.yaml` file). If a contest is configured with problems having different compilation time limits, the approach taken in the PR will not work.
> 
> Is there an existing substitution variable that could be used (instead of a hard-coded time limit) to solve this issue?

There is a {:timelimit} expansion.

**Comment by johnbrvc** [comment]
> As I understand it, the usage of this script would be to prepend it to a given _language_ definition. However, it is accepting a hard-coded numeric argument for compilation time, which is a per-_problem_ attribute (see the CLICS specification for the Problem Package Format; specifically, the [limits section](https://icpc.io/problem-package-format/spec/problem_package_format#limits) of the `problem.yaml` file). If a contest is configured with problems having different compilation time limits, the approach taken in the PR will not work.
> 
> Is there an existing substitution variable that could be used (instead of a hard-coded time limit) to solve this issue?

There is currently no way use a specific compile time limit as specified in the `problem.yaml` file.  As the title of the PR indicates, this is an **_INTERIM_** fix.  When the real fix implemented, it will, of course, obey the CLICS spec for per-problem limits of `compilation_time `and `compilation_memory`.  Until then, you'll have to use the `timelimit `as @troy2914 pointed out, or, hardcode a constant compile time for all problems in the language definition.

**Comment by troy2914** [comment]
> > As I understand it, the usage of this script would be to prepend it to a given _language_ definition. However, it is accepting a hard-coded numeric argument for compilation time, which is a per-_problem_ attribute (see the CLICS specification for the Problem Package Format; specifically, the [limits section](https://icpc.io/problem-package-format/spec/problem_package_format#limits) of the `problem.yaml` file). If a contest is configured with problems having different compilation time limits, the approach taken in the PR will not work.
> > Is there an existing substitution variable that could be used (instead of a hard-coded time limit) to solve this issue?
> 
> There is currently no way use a specific compile time limit as specified in the `problem.yaml` file. As the title of the PR indicates, this is an **_INTERIM_** fix. When the real fix implemented, it will, of course, obey the CLICS spec for per-problem limits of `compilation_time `and `compilation_memory`. Until then, you'll have to use the `timelimit `as @troy2914 pointed out, or, hardcode a constant compile time for all problems in the language definition.

as you noted there is no support to load the compile timeout or store the compile output,  it should be set to the highest of the system and problem level compile limits.

**Review by clevengr — APPROVED** [review]
Approving based on the understanding that this is an "interim" fix, for #607 and we still have #425 regarding the need for a full implementation (including per-problem, and including both YAML and UI versions).

**Pull request merged**
