### PR TITLE
i107: updated Admin Guide and WhatsNew with V9.7 info.

### LINKED ISSUE #107: Add V9.7 updates to Admin Guide and WhatsNew docs
The PC2 Contest Administrator's Guide needs to have a new sections for the following topics:
- Web Team Interface (WTI) project.  This should probably _replace_ the existing documentation on the (old) "EWTeam".
- Shadow Mode
- Public/Judges scoreboards (support for "freezing" the scoreboard)

The What's New document also needs to be updated to reflect the addition of the above features.

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Updates the Admin Guide and WhatsNew documents with information on the following:

- WTI.  Also replaces most references to EWTeam with corresponding WTI info (although some EWTeam information was retained for historical purposes).  
- Shadow Mode.
- Support for frozen scoreboards.
- Support for user customization of login screens.
- Updated the minimum Java requirement in the manual to Java Version 8.

### Issue which the PR fixes
Fixes #107 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
MS Word on Windows 10.

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
Examine the Admin Guide and WhatsNew PDFs; 
1. Verify that the Admin Guide contains:
   - updated Appendix N covering WTI instead of EWTeam.
   - new Appendix Q covering User Customization of login screens.
   - new Appendix R covering Shadow Mode.
   - updated Chapter 10 covering support for frozen scoreboard displays.

1. verify that the WhatsNew.pdf contains a bullet item regarding each of the above topics.

### CODE REVIEW

**Comment by ashoos72** [comment]
The What's New looks good.

In the Admin guide, two comments:
Page 138, last sentence in the second paragraph, ending in "no additional software needs to be installed on the team machines to run a contest using PC2". Does this imply your don't need to install Java, C, C++ or any other development IDE's or tools to "run a contest using PC2". I think this may need to be reworded slightly.

On the same page, regarding the sentence "By default the WTI expects to use account “scoreboard2” with password “scoreboard2”, should we include "strongly recommend you change the default password". So that random people can't login using the default account/password.

**Comment by clevengr** [comment]
...
> In the Admin guide, two comments:
> Page 138, last sentence in the second paragraph, ending in "no additional software needs to be installed on the team machines to run a contest using PC2". Does this imply your don't need to install Java, C, C++ or any other development IDE's or tools to "run a contest using PC2". I think this may need to be reworded slightly.

Well, I sort of thought that was covered by "no **_additional_** software.   But I see the point.  How about "no additional software needs to be installed on the team machines in order to connect to the PC2 server"?

> 
> On the same page, regarding the sentence "By default the WTI expects to use account “scoreboard2” with password “scoreboard2”, should we include "strongly recommend you change the default password". So that random people can't login using the default account/password.

Sure, I'll add a warning about that...

**Comment by clevengr** [comment]
Note to reviewers:   I am expanding this PR to cover ALL updates to the Admin Guide and WhatsNew documentation.  At the moment it's only partially complete in this regard.  I'll post another comment when I've finished adding all the other items to the docs.

**Comment by clevengr** [comment]
I have now updated the Admin Guide to address Sam's comments (above), and I've added updates to Chapter 10 (Scoreboards) documenting the use of XSL files and XML attributes which can be accessed/used by the XSL files.  I believe this addresses all stated concerns with this PR, so a review of the Admin Guide changes and approval of the PR would be appreciated so I can move on to other things :)

**Comment by clevengr** [comment]
> The DSA shows end of line changes and is a mess.

The minor changes introduced by adding javadoc apparently caused a major EOL issue, which is not worth worrying about as far as this PR is concerned.  I have removed the commit which changed the (javadoc in the) DSA, and pushed the update (that is, I removed the commit via an interactive rebase and then pushed the changes to my branch).   However, the DSA.java file still appears in the  "Files Changed" list.  There is a menu item there which allows "Delete File" -- but I'm not sure if that deletes it just from the PR, or from the repo (the latter would be bad).  Any suggestions?

**Comment by troy2914** [comment]
Delete file is from the repo, you don't want to do that.

**Comment by troy2914** [comment]
honestly i would probably rebase the 11 commits to a one 1 commit.   Then edit that commit, to revert the DSA to the develop version.  and/or `git rm --staged DSA.java`

**Comment by troy2914** [comment]
Also gitub is saying this PR has conflicts.

**Comment by troy2914** [comment]
[How to Remove files from git commit](https://devconnected.com/how-to-remove-files-from-git-commit/)

again highly recommend you are dealing with a single commit when you do that.

**Comment by clevengr** [comment]
> Also gitub is saying this PR has conflicts.

Where do you see conflicts?   All I see is the message "This branch has no conflicts with the base branch"...

**Comment by clevengr** [comment]
Closing this PR to solve issues with deleting the commit of DSA.java; will open a new PR.

**Pull request closed without merging**
