### PR TITLE
i95: Added draft "history" and "permission" pages for website

### LINKED ISSUE #95: Github.io website should include additional pages from old website
**Is your feature request related to a problem?** 
No, it's more of an incompleteness in the current website.

**Feature Description**
The [old ECS website](https://pc2.ecs.csus.edu/) had numerous pages accessible from the "Home Page".  Most of these have already been incorporated, in some form or the other, into the [new website](pc2ccs.github.io).  However, at least two old pages so far don't have anything equivalent on the new site:

- [The (somewhat abridged) history of PC&sup2;](https://pc2.ecs.csus.edu/pc2history.html)
- [Permissions](https://pc2.ecs.csus.edu/pc2permission.html)

It seems reasonable that we would want these pages to move forward to the new website.  

One thing that needs to be considered is "in what form?" In particular, while the "History" page can probably be transferred more-or-less "as-is", the "Permissions" page needs to be rewritten to get across the proper sentiment in the new "open-source" reality -- that technically the system is governed by the EPL 2.0 license, and practically speaking "we would consider it unacceptable if you were trying to use it to make a profit"...

**Have you considered other ways to accomplish the same thing?** 
An alternative is to NOT port either of those pages...

...

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Adds new "history" and "permission" pages to the website **/content** folder.

### Issue which the PR fixes
Fixes #95 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 10 using Eclipse 2019-12.

### Additional info:
All this PR does is define new pages (files) in the **/content** folder.  The added pages are _static_; they don't contain any references to other website data (such as required **layout** information).  I don't _think_ there are any other changes which need to be done to add these pages (but I could be wrong; if so, someone please comment in a review).

### CODE REVIEW

**Comment by troy2914** [comment]
- [ ]  update sed on line 221 of .gitlab-ci.yml to include new pages.

otherwise the PC&sup2; is not rendered properly.   And was it intentional to list these pages above the All Builds page?

**Comment by clevengr** [comment]
> * [ ]   update sed on line 221 of .gitlab-ci.yml to include new pages.
> 
> otherwise the PC² is not rendered properly. 

Fixed; added those files to the sed command.  Also, please review https://github.com/pc2ccs/pc2v9/wiki/Building-the-PC2-GitHub-Website/_edit#webpage-post-processing to verify that I've updated the Wiki description correctly.

> And was it intentional to list these pages above the All Builds page?

No; I missed the fact that "All Builds" had a much larger weight number.  I've set the weights for "History" and "Permission" to be even higher (so they'll display lower).   Please re-review (and approve if appropriate).

**Comment by clevengr** [comment]
BTW, do I not understand "sed" correctly, or is it the case that if there are two (or more) occurrences of "&amp;" on a given line in the index.html files then only the FIRST one of those will be corrected?

**Comment by troy2914** [comment]
> BTW, do I not understand "sed" correctly, or is it the case that if there are two (or more) occurrences of `&amp;` on a given line in the index.html files then only the FIRST one of those will be corrected?

I don't believe that is an issue before my #93,  where i have that fixed.

**Comment by troy2914** [comment]
Seems we should have some history after 2009.  Regionals, SuperRagional usage.

**Comment by clevengr** [comment]
> Seems we should have some history after 2009. Regionals, SuperRagional usage.

I don't disagree; that's why I put the line at the very top about this being documentation of "the first two decades".  We can remove that, and add more (recent) history.  But I will take a while for someone to dig through and find that information, then add it to the web page.  I would like to move on to more important things at the moment, so unless you are going to tackle doing that right away I suggest we approve this and move on...

**Pull request merged**
