### PR TITLE
i532: add Scoreboard JSON Report

### LINKED ISSUE #532: Add new report that for CLICS API scoreboard.json
**Is your feature request related to a problem?** 

No, just a change in how to get a scoreboard.json file.

At this time one must start the API (via feeder) and authenticate
and fetch the scoreboard.json

Add the scoreboard.json as a report so an Admin can save
the file, rather than having to startup a feeder client.

**Feature Description**: 

Add a new Report "Scoreboard JSON" that will output the CLICS API scoreboard.json

**Have you considered other ways to accomplish the same thing?** 

Yes, no others.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add a new Report "Scoreboard JSON" 

**Additional context**:

### PR DESCRIPTION
**Pull request by lane55**
### Description of what the PR does

Adds Scoreboard JSON Report on UI and in CLI Reports

### Issue which the PR fixes

Fixes #532 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Microsoft Windows [Version 10.0.19044.1889]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Use the Reports tab or pc2report to use/print Scoreboard JSON report.

This should match the CLICS API endpoint scoreboard  (via the Feeder)

### CODE REVIEW

**Review by johnbrvc — COMMENTED** [review]
I tried running this on your branch.
The problem I see is that when it brings up the the view of the JSON report, the entire report is on a VERY long single line, making the view essentially useless.  It would be nice if it looked like the scoreboard.json found in results/scoreboard.json (attached in zip), where each record is on its own line in the view.   Looking at the file produced by the Scoreboard JSON in the reports folder (attached here as a zip) it is one single long line.
[report.Scoreboard_JSON.03.20.987.zip](https://github.com/pc2ccs/pc2v9/files/11023524/report.Scoreboard_JSON.03.20.987.zip)
[results_scoreboard.zip](https://github.com/pc2ccs/pc2v9/files/11023527/results_scoreboard.zip)

**Comment by lane55** [comment]
This report is a direct use of the scoreboard end point, which returns a single JSON string on one line.

**Comment by johnbrvc** [comment]
> 

Yes, I saw that.  It generates XML, then converts it to JSON.  I guess the question I'm asking is, what is the purpose of this report if you can't view it?  Is it just to generate a scoreboard json?  isn't that already done by the scoreboard client in the results folder?
If the intent is to simply generate a json, then it seems the header and trailer should be omitted all the time, since the report file is essentially not viewable by a human, so why add the header and trailer?

**Comment by lane55** [comment]
One intent of the report is to provide the same JSON as the scoreboard end point
(ex curl -u admin:admin --insecure https://localhost:50443/contest/scoreboard  )
From the description in

**Comment by lane55** [comment]
In order to format the JSON to be a nljson there are a couple of options:
1 - add an option to the report to output nljson (like for XML)
2 - add an option in the file viewer to display the contents in nljson form
In that way all JSON output (like for other endpoints) would benefit from those options.

**Comment by johnbrvc** [comment]
> 

Agreed.  That can be an enhancement for a future time.
Other than that, I'm fine with the PR.  It does what it is supposed to.

**Review by johnbrvc — APPROVED** [review]

**Pull request merged**
