### PR TITLE
I816 coding style guidelines does not exist. hyperlink broken

### LINKED ISSUE #816: Coding Style Guidelines Does not Exist. Hyperlink Broken
**Describe the issue**: "PC^2 Coding Style Guidelines document" hyperlink found in [CONTRIBUTING.MD](https://github.com/pc2ccs/pc2v9/blob/develop/CONTRIBUTING.MD#codingstyle), specifically in "Coding Style", leads to a 404. There is also another same hyperlink that is broken found in "Pull Request Submission Guidelines"

**Expected behavior**: Should lead to that document.

**Actual behavior**: 404

**Environment**: N/A

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does

Replaces the bad links to a non-existent document (`CodingStyle.md`) in the `Contributing.md` top-level description file with links to appropriate sections of existing documentation.

At some point in the past, many of the PC2 Wiki pages from the old CSUS ECS wiki were converted to GitHub wiki pages.  At the time that was done, it was anticipated that a new "CodingStyle" document (wiki page) would also be created.  However, that never happened.  I have spent hours combing the old ECS wiki/dev_wiki pages and found no such document; the closest I found was [this page](https://pc2.ecs.csus.edu/devwiki/index.php/Development_Standards) which mentions a few things about JUnits and Java Code.  _All_ of the things mentioned on that page have already been included in various sections of the much larger [Development Standards page](https://github.com/pc2ccs/pc2v9/wiki/Development-Standards), so this PR replaces the bad links to the (non-existent) page with links to the appropriate section of that document.

The PR also includes a CI step of adding to the `Contributing.md` file a couple of references to the GitHub "Good First Issue" label, which didn't exist at the time the `Contributing.md` document was first created.

### Issue which the PR addresses

Fixes #816 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Windows 11, Eclipse Version: 2023-03 (4.27.0) Build id: 20230309-1520

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

- Open the PC2 "Contributing" document at https://github.com/clevengr/pc2v9/blob/i816_Coding_Style_Guidelines_Does_not_Exist._Hyperlink_Broken/CONTRIBUTING.MD.
- Scroll down to the `Coding Style` section (or just click on the `Coding Style` link in the first section of the document).
- In the last sentence under `Coding Style`, click on each of the (now four) links and verify that each one of them links to a valid page.
- CI: scroll down to the `Your First Code Contribution` section and verify that the inclusion of the label `good first issue` is present and that the section reads properly.

### CODE REVIEW

**Review by johnbrvc — CHANGES_REQUESTED** [review]
The link for **CLICS Event Feed** still refers to _clics.ecs.baylor.edu_ under **Code Organization**.
Other than that, it seems good.  All the other links appear to work.

**Review by johnbrvc — APPROVED** [review]

**Comment by clevengr** [comment]
> The link for **CLICS Event Feed** still refers to _clics.ecs.baylor.edu_ under **Code Organization**. 

Fixed; it now points to the CLICS website.  However, there's a potential long-term problem:  unlike in the past where there was a stable link to the top level of the CLICS spec, there are now links to each separate "version" (e.g. 22-07).  I chose that link (22-07), but at some point it wouldn't surprise me that it goes bad.

**Review by troy2914 — APPROVED** [review]
I looked at the existing broken stuff,  then i tested the new page, and everything was fixed.

**Comment by clevengr** [comment]
PR has two approvals; merging.

**Pull request merged**
