### PR TITLE
i729-Corrected states for Language ExecutableFilenameTextField and Update button, fixes #729

### LINKED ISSUE #729: Edit Language Dialog does not properly enable the Update button
**Describe the issue**: 
When attempting to edit a language, if the "**Executable Filename**" edit text field is modified, the "**Update**" button is not enabled like it is when the other fields are modified.   In addition, the initial "enabled" state of the "**Executable Filename**" edit text field is incorrect if the check box for "**Script or Interpreted Language**" is unchecked, and, its state is screwed up from that point (just the opposite whenever the check box is toggled).

**To Reproduce**: 
Start from a new Administrator session:
1) Edit a language.
2) Type something in the "**Executable Filename**" field.  Notice the "Update" button does not become enabled.
3) Click on the "**Script or Interpreted Language**" check box.  Note the incorrect "enabled" state of the "**Executable Filename**" text edit area.

**Expected behavior**: 
When characters are typed in the "**Executable Filename**" field, the "**Update**" button should become enabled.
The initial state of the "**Executable Filename**" field should be based on whether the "**Script or Interpreted Language**" is checked or not.

**Actual behavior**: 
See Description above.

**Environment**: 
All.

**Log Info**:  
N/A

**Screenshots**:  
The first screen cap shows the initial state of the "**Executable Filename**" edit text area does not match the check state of the "**Script or Interpreted Language**".  The second screen cap shows that after typing **`XXX`** in the "**Executable Filename**" field, the "**Update**" button is not enabled.

**Additional context**:
The reason the "**Update**" button does not become enabled when the "**Executable Filename**" edit text area is changed is because `Language.isSameAs()` does not check to see if the `executableIdentifierMask `member has changed.  This is because it was probably added at some later point, and the `isSameAs `routine was never updated.

The initial state of the "Executable Filename" edit text area is always enabled, no matter what the state of the "**Script or Interpreted Language**" is.  This is what screws up the "enabled" state of the "**Executable Filename**" edit text area.
EditLang
EditLang2

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
The initial state of the `ExecutableFilenameTextField `is now set based on the value of the _interpreted_ language check box. The correct state is also maintained when the check box is toggled. Added `executableIdentifierMask `to things to compare for equality in `Language`.

### Issue which the PR addresses
#729 
### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11 / Ubuntu 22.04 (Tested)
Java jre1.8.0_321

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
Start from a new Administrator session:

1) Edit a language.
2) Type something in the "**Executable Filename**" field. Notice the "**Update**" button **does** become enabled.  Backspace over the the text entered.  Notice the "**Update**" button reverts to disabled.
3) Click on the "**Script or Interpreted Language**" check box. Note the _correct_ "**enabled**" state of the "**Executable Filename**" text edit area.  That is, if the box is checked, the "**Executable Filename**" is disabled.  If the box is unchecked, the "**Executable Filename**" is enabled.

### CODE REVIEW

**Review by lane55 — APPROVED** [review]
Approved

**Review by troy2914 — APPROVED** [review]
failed test on 6551,  looks good and passes test on this PR.

**Comment by johnbrvc** [comment]
Added separate label for the judge command checkbox and judge command line.  Only enable judge command line label/textbox if checkbox is checked as per image below.
judgecmd

**Review by lane55 — APPROVED** [review]
Approved fix for Edit Language

**Pull request merged**
