### PR TITLE
I528 shadow unable to fetch submission files

### LINKED ISSUE #528: Shadow unable to fetch files for submission(s)
**Describe the issue**: 

When the shadow attempts to fetch files the DOMJudge CCS API,fails to return the files (zip).

The file is fetched by pc2 shadow using a URL of the form:
http://<IPADDR>/domjudge/api/v4//contests/2/submissions/1/files
That will fail, the shadow is configured with: http://<IPADDR>/domjudge/api/v4/ for the Primary CCS URL field

The URL that will succeed is (This is per the CCS API Spec).
http://<IPADDR>/domjudge/api/v4/contests/2/submissions/1/files

Note that there is one slash after the /v4 in the path. Note that Kattis does fetch files given the URL 

**To Reproduce**: 

todo: State Version of DOM Judge
todo: state version of pc2

Configure both DOM Judge and pc2 as shadow

todo: configure DOM Judge
* In Config, set Data Source field to Configuration Data External   (the default is All Local, which will not output the latest CCS EF)

todo:: configure pc2 as shadow, start shadowing

**Expected behavior**: 

The files for the submission should be fetched and submitted to pc2 server.

**Actual behavior**: 

todo assuming: Files not fetched and the submission could not be added to the pc2 server.

See Log info below for example of exception/error message

**Environment**: 

**Log Info**: 

upon failure to read API end point
 
220830 172111.227|INFO|RemoteEventFeedMonitorThread|log|Fetching files from remote system using id 1
220830 172111.246|WARNING|RemoteEventFeedMonitorThread|log|Exception processing event: {"id":"59","type":"submissions","op":"create","data":{"language_id":"cpp","time":"2022-08-30T16:28:01.626-04:00","contest_time":"14553:28:01.626","team_id":"4","problem_id":"3","id":"1","external_id":null,"entry_point":null,"files":[{"href":"contests/2/submissions/1/files","mime":"application/zip"}]},"time":"2022-08-30T16:28:01.680-04:00"}
|java.lang.RuntimeException: java.io.FileNotFoundException: http://10.0.0.169/domjudge/api/v4/contests/2//submissions/1/files
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:281)
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:250)
|    at edu.csus.ecs.pc2.shadow.RemoteEventFeedMonitor.run (RemoteEventFeedMonitor.java:369)
|    at java.lang.Thread.run (Thread.java:750)
**Screenshots**:  

**Additional context**:

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does

Ensures that the URL used by a PC2 Shadow to request a remote Primary CCS to send the files associated with a given submission does not contain an extraneous "/" character between the "Primary CCS URL" and the "submission endpoint name".  This is done by checking the Primary CCS URL (from the current "Contest Settings") and removing any trailing "/" character prior to appending the "submission endpoint name" (which has the form `/submissions/<id>/files`).

### Issue which the PR addresses

Fixes #528

NOTE:  Issue #528 contains very confusing/sketchy information in the "Steps to Reproduce the Issue" section; it has multiple statements marked "todo" which apparently never got done, and it's very vague as to what the actual conditions to reproduce the issue should be.  As a result, the actual issue was very hard (read: unable) to be reproduced based on the information given.  In particular, the Issue references accessing a "Primary CCS" contest running at [http://10.0.0.169/domjudge/api/v4/contests/2](http://10.0.0.169/domjudge/api/v4/contests/2//submissions/1/files), which is clearly some sort of local network contest which can't be replicated (at least, I don't know how).

Since the referenced contest was being run by DOMjudge, I requested (and was granted) access to an available DOMjudge contest running at `https://judge.gehack.nl/api/contests/bapc2022` and tested against that by adding a trailing "/" to the Primary CCS URL in the Admin Settings screen.  Unfortunately, the error listed in the Issue was not reproduced.

Discussions with Nicky brought up the fact that since the original issue was filed (August 2022), DOMjudge has made some updates to the library which they use to process URLs.  The current theory is that their new library handles the "//" sequence in a URL.  As noted in the original issue, Kattis also apparently handled a URL containing "//" correctly.  Therefore, it's possible that the issue which triggered Issue #528 is no longer either present nor is it testable (because there's no longer any remote CCS which can reproduce the problem.

In any case, the fix applied by this PR should not cause any issues (should be benign).  The PR was tested (against the above-mentioned DOMjudge contest, using login "pc2" and a password which won't be documented here but is available from the PR author) both _with_  and _without_ a trailing "/" on the Primary CCS URL; it worked either way.

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Windows 10.1, Java version 11.0.16.1 2022-08-18 LTS

#### Test 1
1. Start a PC2 server.  with bapc2022 CDP config
2. Start a PC2 admin 
  - Create 300 team accounts (because the DOMjudge contest has this many teams)
  - Change the "alias" of team 300 to "domjudge"  (because the DOMjudge contest will submit a bunch of "test" runs to this account)
  -  create 1 FEEDER account
  - Specify a "Primary CCS URL" of `https://judge.gehack.nl/api/contests/bapc2022/` (note the extra "/" at the end).
  - Check Enable CCS Test mode
  - Check Enable Shadow mode
 - Start Contest Clock
4. Start a PC2 Feeder client
5. On the Feeder client, start Shadowing
6. Wait a while until the Feeder pulls all the DOMjudge "test" runs and then starts fetching "real submissions"
7. On the Admin, verify that team submissions are received.  In particular, trying judging a submission and verify that the "submission files" were properly fetched.
8. Examine the FEEDER log; verify that the Exception which was documented in the original Issue:
```
220830 172111.227|INFO|RemoteEventFeedMonitorThread|log|Fetching files from remote system using id 1
220830 172111.246|WARNING|RemoteEventFeedMonitorThread|log|Exception processing event: {"id":"59","type":"submissions","op":"create","data":{"language_id":"cpp","time":"2022-08-30T16:28:01.626-04:00","contest_time":"14553:28:01.626","team_id":"4","problem_id":"3","id":"1","external_id":null,"entry_point":null,"files":[{"href":"contests/2/submissions/1/files","mime":"application/zip"}]},"time":"2022-08-30T16:28:01.680-04:00"}
|java.lang.RuntimeException: java.io.FileNotFoundException: http://10.0.0.169/domjudge/api/v4/contests/2//submissions/1/files
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:281)
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:250)
|    at edu.csus.ecs.pc2.shadow.RemoteEventFeedMonitor.run (RemoteEventFeedMonitor.java:369)
|    at java.lang.Thread.run (Thread.java:750)
```
is not present in the log.

#### Test 2
1. Repeat the above, except remove the trailing "/" from the Primary CCS URL string.
2. Verify that submission files are still properly received on the PC2 Server.
3. Verify that the FEEDER log does not contain exceptions when fetching submission files.

### CODE REVIEW

**Review by troy2914 — APPROVED** [review]
Code review looked reasonable to me,  says someone that has slept 1 hour in the past 21 hours.

**Review by johnbrvc — APPROVED** [review]
Yep.  Seems to work.

**Comment by lane55** [comment]
Updated Shadowing setup settings,   Use CDP bapc2022 ,  create 1 FEEDER account,  Check Enable CCS Test mode, etc.

**Comment by lane55** [comment]
Testing note, changed to   alias from display name.
The shadow matches the teamNNN and the alias (both would be used as logins)

- Change the "alias" of team 300 to "domjudge"  (because the DOMjudge contest will submit a bunch of "test" runs to this account)
from   - Change the "display name" of team 300 to "domjudge"  (because the DOMjudge contest will submit a bunch of "test" runs to this account)

**Comment by clevengr** [comment]
> Testing note, changed to alias from display name. The shadow matches the teamNNN and the alias (both would be used as logins)
> 
> * Change the "alias" of team 300 to "domjudge"  (because the DOMjudge contest will submit a bunch of "test" runs to this account)
>   from   - Change the "display name" of team 300 to "domjudge"  (because the DOMjudge contest will submit a bunch of "test" runs to this account)

I don't object to this change, but it wasn't necessary for me -- I changed the "display name" of team300 to "domjudge" and that allowed the Shadow to ignore the submissions (instead of throwing a "no such account" exception).

**Comment by lane55** [comment]
Passed test 1 and test 2

**Comment by lane55** [comment]
testing note, there were also submissions by team 'jury'

**Review by lane55 — APPROVED** [review]
Approved.

Tested PR (test 1 and 2), added required steps to Test 1 
including that the account alias not display name will be used to match/find account.

**Pull request merged**
