### PR TITLE
Exclude teams not displayed on scoreboard, fixes #588

### LINKED ISSUE #588: The results.tsv file includes teams that are not supposed to be shown on the scoreboard
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**:
If a team does not have the DISPLAY_ON_SCOREBOARD property set, it is still included in the results.tsv file.  It should not be. 

**To Reproduce**: 
Load a contest.
Create teams, and mark one or more as "not shown on scoreboard"
Submit some (successful) runs by teams that shown on the scoreboard.
Submit some (successful) runs by teams that are not shown on the scoreboard.
Let them get judged.
Finalize the contest.
Look at the results.tsv file.  The teams not shown on the scoreboard will be shown in the results.tsv file.

**Expected behavior**: 
Only those teams that are shown on the scoreboard should appear in the results.tsv file. 

**Actual behavior**:
Teams marked as not shown on the scoreboard appear in the results.tsv.  This can cause incorrect rankings of
teams that ARE shown on the scoreboard

**Environment**:
All.

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: 
The exports/ccs/ResultsFile.java uses the NSA to generate the results.tsv.  This does not look at the shown on scoreboard permission.
[results.txt](https://github.com/pc2ccs/pc2v9/files/9957498/results.txt)

### PR DESCRIPTION
**Pull request by johnbrvc**
Teams that are not displayed on the scoreboard should be excluded from the generated results.tsv. This involves creating a new vector that consists only of those teams that are displayed on the scoreboard and using that for the standings computations.

Before submitting your Pull Request, please make sure you have read the [Guidelines for Submitting Pull Requests](https://github.com/pc2ccs/pc2v9/wiki/Guidelines-for-Submitting-Pull-Requests).  Then please provide the following information:

### Description of what the PR does
Only includes those teams that are displayed on the scoreboard in the results.tsv.  This is done in the core.scoring.NewScoringAlgorithm.

### Issue which the PR fixes
Fixes #588 
### Environment in which the PR was developed (OS,IDE, Java version, etc.)
OS              : Windows 7 6.1 (amd64)
Java Version    : 1.8.0_322
(Yes, you read right: that IS Windows 7)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
Load a contest.
Create teams, and mark one or more as "not shown on scoreboard"
Submit some (successful) runs by teams that shown on the scoreboard.
Submit some (successful) runs by teams that are not shown on the scoreboard.
Let them get judged.
Finalize the contest.
Look at the results.tsv file. The teams not shown on the scoreboard will **NOT** be in the results.tsv file.

### CODE REVIEW

**Review by lane55 — APPROVED** [review]
Approved.
Created unit test testNSDAwithNotDisplayTeams (locally) to test change.

**Comment by lane55** [comment]
Here is source code for unit test for #588 
[NSATest.snippet.588.java.txt](https://github.com/pc2ccs/pc2v9/files/10035517/NSATest.snippet.588.java.txt)

**Review by clevengr — APPROVED** [review]

**Comment by clevengr** [comment]
Two approvals; merging.

> Here is source code for unit test for #588 [NSATest.snippet.588.java.txt](https://github.com/pc2ccs/pc2v9/files/10035517/NSATest.snippet.588.java.txt)

@johnbrvc  can you copy Doug's JUnit into your branch, run it to verify it works, and push it?   It seems like we should capture this before we merge the PR.

**Comment by clevengr** [comment]
This change is important enough that we want it included in the version to be used for ACPC (in three days).   @johnbrvc has agreed to create a separate issue/PR for adding the JUnit test, so this PR is complete; merging now.

**Pull request merged**
