### PR TITLE
I 496 aj run flow redesign

### PR DESCRIPTION
**Pull request by lane55**
### Description of what the PR does

Initial work on AJ redesign.   New Data/Lists added.  Minimal code.

Added new report (only works on the Server UI at this time): Autojudge Lists Report
which shows the current AJ list and contents.    Since the AJ lists are only stored
on the server, at this time the Autojudge Lists Report is the only way to examine the lists.

### Issue which the PR fixes

Someday #496

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Config server for auto judging contest
Submit runs
Runs should be auto judged.

### CODE REVIEW

**Comment by johnbrvc** [comment]
Picky, defensive programming things: In AutoJudgeManager::findRunToAutoJudge(), I might protect each step of the list removals with their own try/catch and attempt some kind of recovery if one step should fail.  I also may change the order of the removes.  That is, remove the judge from the judge list availableAJList first, THEN the run from the availableAJRunList.  The run list is more important than the judge list, so if the judge remove causes an exception, the run isn't lost forever.  Similarly, if the contest.getRun() should fail, we'd probably want to re-add the judge back to the AvailableAJList so it's not lost forever; the run in this case isn't as important since it's probably bad anyway if the getRun() failed - no great loss.

**Comment by johnbrvc** [comment]
In AutojudgeListReport, it may be nice to include the problem Letters in addition to the short name in the output.

**Comment by lane55** [comment]
> Picky, defensive programming things: In AutoJudgeManager::findRunToAutoJudge(), I might protect each step of the list removals with their own try/catch and attempt some kind of recovery if one step should fail. I also may change the order of the removes. That is, remove the judge from the judge list availableAJList first, THEN the run from the availableAJRunList. The run list is more important than the judge list, so if the judge remove causes an exception, the run isn't lost forever. Similarly, if the contest.getRun() should fail, we'd probably want to re-add the judge back to the AvailableAJList so it's not lost forever; the run in this case isn't as important since it's probably bad anyway if the getRun() failed - no great loss.

Agreed.  Will updae code and then push.

**Comment by lane55** [comment]
> In AutojudgeListReport, it may be nice to include the problem Letters in addition to the short name in the output.

Pushed fir that adds letter to start of short name, Ex.
There are 1 Judges available in Auto Judge list
    JUDGE4 @ site 1 2 problems: A - hello, B - sumit
There are 0 Runs in Auto Judge list

**Comment by lane55** [comment]
> Picky, defensive programming things: In AutoJudgeManager::findRunToAutoJudge(), I might protect each step of the list removals with their own try/catch and attempt some kind of recovery if one step should fail. I also may change the order of ...
Pushed new re-ordered removes and defensive code.

**Review by johnbrvc — COMMENTED** [review]
This is more or less a test comment to see if it starts a conversation.  Seems correct.

**Review by johnbrvc — CHANGES_REQUESTED** [review]
This is more or less another test comment (using Request Changes) to see if it starts a conversation.

**Comment by lane55** [comment]
closing pull request.  This was a preview, when more work updated/done will push another PR

**Pull request closed without merging**
