### PR TITLE
i859: update button titles and tool tips

### PR DESCRIPTION
**Pull request by lane55**
### Description of what the PR does

On Judging Utilities tab update component names and tool tips

### Issue which the PR addresses

#859 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Microsoft Windows [Version 10.0.22621.2428]

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

start server
start admin
Run Contest tab
Judging Utilities tab

Changes
Rename Submit button "Update judgement"
Add tooltip "Rejudge selected runs" to Rejudge button
Add tooltip "Update judgements on selected runs" to Update judgement

### CODE REVIEW

**Review by johnbrvc — APPROVED** [review]
Works as described.  However, I always wondered _why_ every single spelling of "judgment" in PC2 is wrong.  The correct, **US** spelling is "judgment", not "judgement".   Using "judgement" would be like spelling color as colour or analyze as analyse or program as programme - we just don't do that in the US.  It just irritates me every time I see it.  --rant off--

**Review by clevengr — APPROVED** [review]
I would have liked to see the JButton component _name_ changed, from `judgementSubmittedButton` to something like `judgmentUpdatedButton`, to match the change in functional labeling (this is a 5-second refactor operation in Eclipse...)   However, I'm ok with it as-is if no one wants to take the time to make that change.

One problem I had: I could not find the branch `i_859_update_Judge_Utilities_component_names` in my clone of Doug's fork.  I did a pull; it said "Nothing to update".  But when I try to switch to that branch, it's not listed in "Other>RemoteTracking".   I had to completely delete and reclone Doug's repo to get access to the branch.  Very strange...  

In any case, the code changes are clear and trivial, and I'm fine with them.    

One note: pressing the newly-labeled "Update Judgement" button when there are no runs selected still displays a Status Panel message saying "Please select run to be judged".  I think that message should also be changed to reflect that the button doesn't actually JUDGE the runs but rather _changes the judgement assigned to the runs_.

**Comment by clevengr** [comment]
> Works as described. However, I always wondered _why_ every single spelling of "judgment" in PC2 is wrong. The correct, **US** spelling is "judgment", not "judgement". Using "judgement" would be like spelling color as colour or analyze as analyse or program as programme - we just don't do that in the US. It just irritates me every time I see it. --rant off--

This is probably historically my fault.  I always thought "judgment" looked wrong and "judgement" looked right, so that's the way I've always written it in the documentation.  Perhaps it somehow carried across to the code as well...

**Comment by lane55** [comment]
two approvals merging

**Pull request merged**
