### PR TITLE
I460 update docs for 9.8

### LINKED ISSUE #460: Update documentation in prep for 9.8 release
This Issue is for tracking changes to the Admin Guide and WhatsNew documents in preparation for generating a 9.8 Release Candidate and subsequently a stable release.

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does

Updates the Admin Guide and What's New docs with changes which have been made since the last doc update in September.

### Issue which the PR fixes

Fixes #460 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Windows 10.1, MS Word 365.

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Well, for anybody that wants to do it:

- Open the updated WhatsNew document and verify that it contains new entries under "What's New in Version 9.8" for the following PRs which have been merged since September (this is precisely the checklist I used to manage updating the document):

  - 499:  Add doc for defining/adding sites using YAML
  - 291:  Add doc on team Scoreboard Display Format settings
  - 547:  Contest vs. Event Feed model comparison report
  - 549:  Shadow reconnect to Primary, GUI updates showing EF status
  - 553:  Do not start shadowing if local contest clock is stopped
  - 554:  Add Ant targets to skip subproject builds.
  - 555:  Fix shadow GUI update delays
  - 566:  Add support for {:problemshort} substitution variable
  - 568:  Add support for :infilename and :ansfilename substitution variables
  - 579:  --load supports automatic location of config directory underneath a root CDP folder
  - 585:  Adjustments for GUI layout issues under Linux
  - 612:  Adjustments for GUI layout issues under Linux
  - 587:  Correct handling of CLICS judgement acronyms
  - 589:  Correct issue where teams not on the scoreboard were incorrectly listed in results.tsv
  - 620:  Corect numerical sorting of teams on Shadow display
  - 622:  Correct test case ordinal numbers in Event Feed
  - 624:  Update /scoreboard web service endpoint to return a CLICS-compatible JSON string
  - 629:  Correct an issue with the contest id handling in the web service start/pause PATCH endpoint used by remote applications to start/pause the contest
  - 633:  Correct an issue where the Event Feed was not outputting "runs" test case events.

- Open the updated Admin Guide and verify that it contains new entries in the indicated locations for the following PRs which have been merged since September (again, this is precisely the list I used for managing the updating):

  - 499:  Add doc for defining/adding sites using YAML (see section 6.8)
  - 291:  Add doc on team Scoreboard Display Format settings (see section 6.7, under "Team Settings")
  - 547:  Contest vs. Event Feed model comparison report (see the table in section 9.6)
  - 549:  Shadow reconnect to Primary, GUI updates showing EF status (see the updated images and text in Appendix R, Section 3)
  - 566:  Add support for {:problemshort} substitution variable (see the Wiki reference at the end of Section 6.4.2, and the Wiki page at https://github.com/pc2ccs/pc2v9/wiki/Substitution-Variables)
  - 568:  Add support for :infilename and :ansfilename substitution variables (see the table in Appendix E, Section 3, along with the references to validator arguments throughout Appendix E and the Wiki page at https://github.com/pc2ccs/pc2v9/wiki/Substitution-Variables)

### CODE REVIEW

**Comment by lane55** [comment]
From footnote on page 161 admin guide
given the Edit a Run permission, which under Version 9.8 can only be
done interactively

With I 450 permissions can be added/disabled in the yaml.

PR 471 - I 450 add yaml load for account permissions 
Just tested it in nightly build Version 9.8build 20221204 (Sunday, December 4th 2022 08:19 UTC) build 6436~develop


With 450 one can set both proxy and edit run thus:

# account permissions
permissions:
  - account: FEEDER
    number: 1
    enable: SHADOW_PROXY_TEAM, EDIT_RUN

Permissions can be added or disabled/removed

See general description of Permissions section at 
https://github.com/pc2ccs/pc2v9/issues/450#issuecomment-1162513058

and the comment below lists all allowed values/Permissions,
which are from Permission.Type class/enum

**Review by johnbrvc — CHANGES_REQUESTED** [review]
In Administrators Guide: Link to CLICS spec gives 404.  This is probably the correct link: https://ccs-specs.icpc.io/2022-07/contest_api#problems
Footnote on pg 161 about only being able to set "edit run" permission interactively isn't accurate.  I believe that any permission can be set in the YAML file (system.pc2.yaml, for example).
```
permissions:
# enable perms for FEEDER 1 to edit runs and submit runs
  - account: FEEDER
    number: 1
    enable: SHADOW_PROXY_TEAM, EDIT_RUN

```
In What's New: Maybe combine "Added support for use of the scroll wheel on tables" and "Updated various grids to use JTables" since the reason for the change to JTable was to use the mouse scroll wheel...

**Comment by clevengr** [comment]
@johnbrvc said:

> In Administrators Guide: Link to CLICS spec gives 404. This is probably the correct link: https://ccs-specs.icpc.io/2022-07/contest_api#problems 

There are many links to CLICS specs in the Admin Guide.  Can you tell me where the one is that you found that isn't working?

> Footnote on pg 161 about only being able to set "edit run" permission interactively isn't accurate. I believe that any permission can be set in the YAML file (system.pc2.yaml, for example).
> 
> ```
> permissions:
> # enable perms for FEEDER 1 to edit runs and submit runs
>   - account: FEEDER
>     number: 1
>     enable: SHADOW_PROXY_TEAM, EDIT_RUN
> ```

Yep, fixed.

> 
> In What's New: Maybe combine "Added support for use of the scroll wheel on tables" and "Updated various grids to use JTables" since the reason for the change to JTable was to use the mouse scroll wheel...

Good idea; done.

**Comment by clevengr** [comment]
> 



> From footnote on page 161 admin guide given the Edit a Run permission, which under Version 9.8 can only be done interactively
> 
> With I 450 permissions can be added/disabled in the yaml.
> 
> PR 471 - I 450 add yaml load for account permissions Just tested it in nightly build Version 9.8build 20221204 (Sunday, December 4th 2022 08:19 UTC) build 6436~develop
> 
> With 450 one can set both proxy and edit run thus:
> 
> # account permissions
> permissions:
> 
> * account: FEEDER
>   number: 1
>   enable: SHADOW_PROXY_TEAM, EDIT_RUN
> 
> Permissions can be added or disabled/removed
> 
> See general description of Permissions section at [#450 (comment)](https://github.com/pc2ccs/pc2v9/issues/450#issuecomment-1162513058)
> 
> and the comment below lists all allowed values/Permissions, which are from Permission.Type class/enum

Yep; fixed (updated Admin Guide, added a description of the usage of "permissions" to the Wiki page).

**Comment by johnbrvc** [comment]
> 

Bad link is in appendix R end of 3rd paragraph.

**Comment by clevengr** [comment]
> > 
> 
> Bad link is in appendix R end of 3rd paragraph.

Fixed.  Sadly, the link was bad because the CLICS group changed the structure of their website.  Previously, it was possible to link to the top level (which is what the bad link referenced).  Now, it's only possible to link to a specific VERSION of the spec.  I changed the bad link to point to the 2022-07 version... which is (and should remain) valid but will (ultimately) be "outdated".

**Comment by clevengr** [comment]
@johnbrvc @lane55 

I have pushed new versions of the WhatsNew and Admin Guide .doc and .pdf files.  They contain corrections for all of the issues which were noted by in previous reviews (above).  They also contain updates for additional Issues/PRs which (as I said in Slack) I discovered I had failed to include in the original PR.  Those include:

  414:  Support loading of problem titles from problem.en.tex files  (see new bullet near the end of WhatsNew in 9.8) 
  457:  Support loading of a custom validator using YAML (see the footnote in Appendix E Section 2)
  524:  Validate command line options (see second paragraph of appendix C)

The updated docs are again ready for review; please let me know if you spot anything that still needs fixing before we merge and create a 9.8 release.

**Review by lane55 — APPROVED** [review]
Approved
Noted: new reference to Permissions in wiki and new example yaml for Permissions  in admin guide

**Pull request merged**
