### PR TITLE
i873: fix junit that should not be a mismatch display name

### LINKED ISSUE #873: Running JUnit `NewScoringAlgorithmTest.java` on WIndows fails
**Describe the issue**: 
When running **JUnit** tests on any build of PC2 after PR #711 , the `edu.csus.ecs.pc2.core.scoring.NewScoringAlgorithmTest` will fail:

image

This is because the team name for Team203 has "funny" characters in it.  On Linux, these cause the display format strings to (apparently) not match.  On Windows, they match correctly.  The team name "☆☆team uwu-est☆☆" formats properly on Windows but evidently not on Linux, and the **JUnit** was written to expect this.  That is, there is code to explicitly expect one mismatch:

```
        int expectedMismatches = 1;

        assertEquals("Expecting mis matched names ", expectedMismatches, mismatches);

```
Reviewing the commits for PR #711, the code had a comment to the effect:

image

The comment has since be deleted.

**To Reproduce**: 
Run **JUnit** test for `NewScoringAlgorithmTest `on a PC2 build AFTER #711.  (The current develop branch will suffice).
Notice the test will fail, but the CI on GitHub works fine.

**Expected behavior**: 
The **JUnit** test should pass on both GitHub (Linux) and Windows.:  

**Actual behavior**: 
The JUnit test passes on GitHub (Linux) but fails on Windows.

**Environment**: 
OS              : Windows 11 10.0 (amd64)
Java Version    : 1.8.0_321
PC2 (9.9 >= PR #711)

**Log Info**: 
**Screenshots**:
(See above, in-line).

**Additional context**:
I (for one) usually never run the **JUnit** tests when developing.  I let Github do that during the CI process.  I noticed this purely by accident when a different **JUnit** failed for a different reason and I was trying to debug it on Windows and came across this problem.

### PR DESCRIPTION
**Pull request by troy2914**
fixes #873

tested with
MacOS 14.1.2 (23B92)
java 1.8 (Amazon Corretto)

steps to test:
run all the junits, they should pass

### CODE REVIEW

**Comment by troy2914** [comment]
nothing i did to pass a LANG seemed to work.   Ended up having the code look for the CI environment variable, to determine how many expectedMismatches there are.

**Comment by troy2914** [comment]
confused why JohnC said the old code worked for him.  old JDK?

**Comment by johnbrvc** [comment]
> confused why JohnC said the old code worked for him. old JDK?

The fix does not work on Windows.   With this PR, on Windows, the test run shows:
`junit.framework.AssertionFailedError: Expecting mismatched names  expected:<0> but was:<1>`

I then added the following lines just before the asserts:
```
        String lang = System.getenv("LANG");
        String path = System.getenv("PATH");
        System.err.println("Lang=" + lang + "  Path:" + path);
        assertEquals("Expecting mismatched names ", expectedMismatches, mismatches);
        assertEquals("Expecting matching names ", 78-expectedMismatches, teamStandings.size() - expectedMismatches);
```
and the output was:
`Lang=null  Path:C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin/server;C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\john\AppData\Local\Microsoft\WindowsApps;C:\Users\john\AppData\Local\GitHubDesktop\bin;C:\Program Files\Java\jdk1.8.0_351\bin;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Eclipse2021-12\eclipse;`

In Eclipse, I then set "`LANG=en_US.UTF-8`" in the Environment in the Run/Debug settings and the JUnit showed this, but still failed:
`Lang=en_US.UTF-8  Path:C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin/server;C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\john\AppData\Local\Microsoft\WindowsApps;C:\Users\john\AppData\Local\GitHubDesktop\bin;C:\Program Files\Java\jdk1.8.0_351\bin;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Eclipse2021-12\eclipse;`

**Comment by troy2914** [comment]
> > confused why JohnC said the old code worked for him. old JDK?
> 
> The fix does not work on Windows. With this PR, on Windows, the test run shows: `junit.framework.AssertionFailedError: Expecting mismatched names expected:<0> but was:<1>`
> 
> I then added the following lines just before the asserts:
> 
> ```
>         String lang = System.getenv("LANG");
>         String path = System.getenv("PATH");
>         System.err.println("Lang=" + lang + "  Path:" + path);
>         assertEquals("Expecting mismatched names ", expectedMismatches, mismatches);
>         assertEquals("Expecting matching names ", 78-expectedMismatches, teamStandings.size() - expectedMismatches);
> ```
> 
> and the output was: `Lang=null Path:C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin/server;C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\john\AppData\Local\Microsoft\WindowsApps;C:\Users\john\AppData\Local\GitHubDesktop\bin;C:\Program Files\Java\jdk1.8.0_351\bin;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Eclipse2021-12\eclipse;`
> 
> In Eclipse, I then set "`LANG=en_US.UTF-8`" in the Environment in the Run/Debug settings and the JUnit showed this, but still failed: `Lang=en_US.UTF-8 Path:C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin/server;C:/Eclipse2021-12/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\john\AppData\Local\Microsoft\WindowsApps;C:\Users\john\AppData\Local\GitHubDesktop\bin;C:\Program Files\Java\jdk1.8.0_351\bin;C:\Users\john\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Eclipse2021-12\eclipse;`
> 
> Added: After some research, and this page here: [Change file encoding](https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding) and this page: [Change language for Java](https://stackoverflow.com/questions/24060071/change-language-in-windows-before-calling-process), I tried running the JUnit using these extra VM args (right click the test.java, Properties, Run/Debug Settings, Edit, and change vm args to: image
> 
> Then, the JUnit runs cleanly since the character encoding is set to UTF-8. I'm not sure we want to do this though, do we?

does that mean my latest commit no longer works?

**Comment by troy2914** [comment]
or should i change my guard to be on whether LANG is set?

**Pull request closed without merging**
