### PR TITLE
cleanup the jquery*.js

### LINKED ISSUE #144: jquery should be only be using minified version.
Currently in develop,  jquery-1.9.1.js is referenced,   though jquery-1.9.1.min.js is also present.
Update the references, and remove jquery-1.9.1.js

difference in file size of the js is 185343 bytes.

also collapse the jquery-ui.js (which is 1.10.1) and the jquery-ui-1.10.2.js

### PR DESCRIPTION
**Pull request by troy2914**
use the smaller jquery-1.9.1.min.js vs the biggeer jquery-1.9.1.js
update jquery-ui.js from 1.10.1 to 1.10.2 and remove the duplicate.

fixes #144

### CODE REVIEW

**Review by clevengr — COMMENTED** [review]
I understand the changes in 9 of the 10 changed files (those switching to `jquery-1.9.min.js` and those eliminating `jquery-ui-1.10.2.js`.  What I don't understand is all the changes to `jquery-ui.js`.  I am neither a JQuery expert nor a JavaScript expert; I'm not qualified to review the 381 changed lines in that file.  Did you actually rewrite those JS functions?  Has this been tested?

**Comment by troy2914** [comment]
The jquery-ui-1.10.2.js was copied over the jquery.js (which contained 1.10.1),  One php (iViewRuns.php) was already using the 1.10.2 version,  the other 5 were using the 1.10.1 version.

**Comment by troy2914** [comment]
above push was to sync with the upstream.

**Comment by clevengr** [comment]
Did you actually build and test a new EWTeam distribution with the updates in this PR?

**Review by ashoos72 — APPROVED** [review]
Tested successfully in local build, built from i_144_cleanup_jquery branch.

looks good.

**Pull request merged**
